import "server-only";

const GRAPH_VERSION = "v21.0";

/**
 * Send an Instagram DM.
 *
 * Uses the Instagram Business Login API format:
 *   POST https://graph.instagram.com/v21.0/me/messages
 *   Body: { recipient: {id}, message: {text}, access_token }
 *
 * (Note: access_token goes in the JSON BODY, not a header or query param —
 * this is the working pattern for IG Business Login tokens.)
 *
 * If `useFacebookGraph` is passed (legacy page access token from Facebook
 * Login flow), falls back to graph.facebook.com.
 */
export async function sendInstagramText(params: {
  pageAccessToken: string;
  recipientId: string;
  text: string;
  igUserId?: string;
  useFacebookGraph?: boolean;
}): Promise<{ messageId?: string }> {
  const host = params.useFacebookGraph ? "graph.facebook.com" : "graph.instagram.com";
  const url = `https://${host}/${GRAPH_VERSION}/me/messages`;

  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      recipient: { id: params.recipientId },
      message: { text: params.text },
      access_token: params.pageAccessToken,
    }),
  });
  const json = (await res.json().catch(() => ({}))) as {
    message_id?: string;
    error?: { message: string };
  };
  if (!res.ok) throw new Error(`Instagram send failed: ${json.error?.message ?? res.statusText}`);
  return { messageId: json.message_id };
}

/**
 * Send a sender_action to Instagram. "typing_on" shows the three-dot
 * typing bubble to the recipient and auto-clears after ~20s or when the
 * next real message arrives. Non-critical — all errors are swallowed.
 */
export async function sendInstagramSenderAction(params: {
  pageAccessToken: string;
  recipientId: string;
  action: "typing_on" | "typing_off" | "mark_seen";
  useFacebookGraph?: boolean;
}): Promise<void> {
  const host = params.useFacebookGraph ? "graph.facebook.com" : "graph.instagram.com";
  const url = `https://${host}/${GRAPH_VERSION}/me/messages`;
  await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      recipient: { id: params.recipientId },
      sender_action: params.action,
      access_token: params.pageAccessToken,
    }),
  }).catch(() => {});
}

export interface InboundInstagramMessage {
  pageId: string; // IG business account id as reported by webhook
  senderId: string; // always the customer's id (even for echoes)
  text: string;
  platformMessageId?: string;
  /**
   * True when this message was sent by the business FROM Instagram directly
   * (not auto-generated by our outbound code). Used to detect when the
   * owner typed stop/start in the IG app to pause the AI.
   */
  isEcho?: boolean;
}

export function parseInstagramWebhook(body: unknown): InboundInstagramMessage[] {
  const out: InboundInstagramMessage[] = [];
  const entries =
    (body as {
      entry?: Array<{
        id: string;
        messaging?: IGEvent[];
        standby?: IGEvent[];
        changes?: Array<{ field: string; value: IGEvent }>;
      }>;
    }).entry ?? [];

  for (const entry of entries) {
    const pageId = entry.id;

    // Meta delivers Instagram DM events via three possible arrays:
    //   entry.messaging[] — classic Messenger-style (Primary inbox)
    //   entry.standby[]   — handover protocol / General inbox
    //   entry.changes[]   — NEW Instagram API format where each change has
    //                        { field: "messages", value: <event> }
    const events: IGEvent[] = [
      ...(entry.messaging ?? []),
      ...(entry.standby ?? []),
    ];
    for (const ch of entry.changes ?? []) {
      if (ch.field === "messages" && ch.value) events.push(ch.value);
    }

    for (const ev of events) {
      if (!ev.message) continue;
      const text = ev.message.text;
      if (!text) continue;
      if (ev.message.is_echo) {
        // Business-originated reply from the IG app. The customer's id is
        // the recipient (not the sender).
        out.push({
          pageId,
          senderId: ev.recipient.id,
          text,
          platformMessageId: ev.message.mid,
          isEcho: true,
        });
      } else {
        out.push({
          pageId,
          senderId: ev.sender.id,
          text,
          platformMessageId: ev.message.mid,
        });
      }
    }
  }
  return out;
}

interface IGEvent {
  sender: { id: string };
  recipient: { id: string };
  message?: { mid?: string; text?: string; is_echo?: boolean };
}
